{
 "title": "System Metrics",
 "tags": [
  "telegraf",
  "system"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "timeAgoNs = uint(v: now()) - uint(v: v.timeRangeStart)\nbucket = if timeAgoNs <= uint(v: 3h) then \"INIT_BUCKET_NAME\"\n  else if timeAgoNs <= uint(v: 36h) then \"INIT_BUCKET_NAME_1min\"\n  else if timeAgoNs <= uint(v: 7d) then \"INIT_BUCKET_NAME_5min\"\n  else if timeAgoNs <= uint(v: 90d) then \"INIT_BUCKET_NAME_1h\"\n  else if timeAgoNs <= uint(v: 365d) then \"INIT_BUCKET_NAME_4h\"\n  else if timeAgoNs <= uint(v: 2190d) then \"INIT_BUCKET_NAME_1d\"\n  else \"INIT_BUCKET_NAME_1w\"\nisRaw = timeAgoNs <= uint(v: 3h)\nfield = if isRaw then \"usage_idle\" else \"usage_idle_mean\"\n\nfrom(bucket: bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == field)\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: 100.0 - r._value }))\n  |> set(key: \"_field\", value: \"cpu_mean\")"
    },
    {
     "query": "timeAgoNs = uint(v: now()) - uint(v: v.timeRangeStart)\nbucket = if timeAgoNs <= uint(v: 3h) then \"INIT_BUCKET_NAME\"\n  else if timeAgoNs <= uint(v: 36h) then \"INIT_BUCKET_NAME_1min\"\n  else if timeAgoNs <= uint(v: 7d) then \"INIT_BUCKET_NAME_5min\"\n  else if timeAgoNs <= uint(v: 90d) then \"INIT_BUCKET_NAME_1h\"\n  else if timeAgoNs <= uint(v: 365d) then \"INIT_BUCKET_NAME_4h\"\n  else if timeAgoNs <= uint(v: 2190d) then \"INIT_BUCKET_NAME_1d\"\n  else \"INIT_BUCKET_NAME_1w\"\nisRaw = timeAgoNs <= uint(v: 3h)\nfield = if isRaw then \"usage_idle\" else \"usage_idle_min\"\n\nfrom(bucket: bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == field)\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: 100.0 - r._value }))\n  |> set(key: \"_field\", value: \"cpu_max\")"
    },
    {
     "query": "timeAgoNs = uint(v: now()) - uint(v: v.timeRangeStart)\nbucket = if timeAgoNs <= uint(v: 3h) then \"INIT_BUCKET_NAME\"\n  else if timeAgoNs <= uint(v: 36h) then \"INIT_BUCKET_NAME_1min\"\n  else if timeAgoNs <= uint(v: 7d) then \"INIT_BUCKET_NAME_5min\"\n  else if timeAgoNs <= uint(v: 90d) then \"INIT_BUCKET_NAME_1h\"\n  else if timeAgoNs <= uint(v: 365d) then \"INIT_BUCKET_NAME_4h\"\n  else if timeAgoNs <= uint(v: 2190d) then \"INIT_BUCKET_NAME_1d\"\n  else \"INIT_BUCKET_NAME_1w\"\nisRaw = timeAgoNs <= uint(v: 3h)\nfield = if isRaw then \"usage_idle\" else \"usage_idle_max\"\n\nfrom(bucket: bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == field)\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: 100.0 - r._value }))\n  |> set(key: \"_field\", value: \"cpu_min\")"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "timeAgoNs = uint(v: now()) - uint(v: v.timeRangeStart)\nbucket = if timeAgoNs <= uint(v: 3h) then \"INIT_BUCKET_NAME\"\n  else if timeAgoNs <= uint(v: 36h) then \"INIT_BUCKET_NAME_1min\"\n  else if timeAgoNs <= uint(v: 7d) then \"INIT_BUCKET_NAME_5min\"\n  else if timeAgoNs <= uint(v: 90d) then \"INIT_BUCKET_NAME_1h\"\n  else if timeAgoNs <= uint(v: 365d) then \"INIT_BUCKET_NAME_4h\"\n  else if timeAgoNs <= uint(v: 2190d) then \"INIT_BUCKET_NAME_1d\"\n  else \"INIT_BUCKET_NAME_1w\"\nisRaw = timeAgoNs <= uint(v: 3h)\nfield = if isRaw then \"used_percent\" else \"used_percent_mean\"\n\nfrom(bucket: bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == field)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"mem_mean\")"
    },
    {
     "query": "timeAgoNs = uint(v: now()) - uint(v: v.timeRangeStart)\nbucket = if timeAgoNs <= uint(v: 3h) then \"INIT_BUCKET_NAME\"\n  else if timeAgoNs <= uint(v: 36h) then \"INIT_BUCKET_NAME_1min\"\n  else if timeAgoNs <= uint(v: 7d) then \"INIT_BUCKET_NAME_5min\"\n  else if timeAgoNs <= uint(v: 90d) then \"INIT_BUCKET_NAME_1h\"\n  else if timeAgoNs <= uint(v: 365d) then \"INIT_BUCKET_NAME_4h\"\n  else if timeAgoNs <= uint(v: 2190d) then \"INIT_BUCKET_NAME_1d\"\n  else \"INIT_BUCKET_NAME_1w\"\nisRaw = timeAgoNs <= uint(v: 3h)\nfield = if isRaw then \"used_percent\" else \"used_percent_max\"\n\nfrom(bucket: bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == field)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> set(key: \"_field\", value: \"mem_max\")"
    },
    {
     "query": "timeAgoNs = uint(v: now()) - uint(v: v.timeRangeStart)\nbucket = if timeAgoNs <= uint(v: 3h) then \"INIT_BUCKET_NAME\"\n  else if timeAgoNs <= uint(v: 36h) then \"INIT_BUCKET_NAME_1min\"\n  else if timeAgoNs <= uint(v: 7d) then \"INIT_BUCKET_NAME_5min\"\n  else if timeAgoNs <= uint(v: 90d) then \"INIT_BUCKET_NAME_1h\"\n  else if timeAgoNs <= uint(v: 365d) then \"INIT_BUCKET_NAME_4h\"\n  else if timeAgoNs <= uint(v: 2190d) then \"INIT_BUCKET_NAME_1d\"\n  else \"INIT_BUCKET_NAME_1w\"\nisRaw = timeAgoNs <= uint(v: 3h)\nfield = if isRaw then \"used_percent\" else \"used_percent_min\"\n\nfrom(bucket: bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == field)\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n  |> set(key: \"_field\", value: \"mem_min\")"
    }
   ]
  },
  {
   "title": "Disk Usage (/)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "timeAgoNs = uint(v: now()) - uint(v: v.timeRangeStart)\nbucket = if timeAgoNs <= uint(v: 3h) then \"INIT_BUCKET_NAME\"\n  else if timeAgoNs <= uint(v: 36h) then \"INIT_BUCKET_NAME_1min\"\n  else if timeAgoNs <= uint(v: 7d) then \"INIT_BUCKET_NAME_5min\"\n  else if timeAgoNs <= uint(v: 90d) then \"INIT_BUCKET_NAME_1h\"\n  else if timeAgoNs <= uint(v: 365d) then \"INIT_BUCKET_NAME_4h\"\n  else if timeAgoNs <= uint(v: 2190d) then \"INIT_BUCKET_NAME_1d\"\n  else \"INIT_BUCKET_NAME_1w\"\nisRaw = timeAgoNs <= uint(v: 3h)\nfield = if isRaw then \"used_percent\" else \"used_percent_mean\"\n\nfrom(bucket: bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == field)\n  |> filter(fn: (r) => r[\"path\"] == \"/\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"disk_mean\")"
    },
    {
     "query": "timeAgoNs = uint(v: now()) - uint(v: v.timeRangeStart)\nbucket = if timeAgoNs <= uint(v: 3h) then \"INIT_BUCKET_NAME\"\n  else if timeAgoNs <= uint(v: 36h) then \"INIT_BUCKET_NAME_1min\"\n  else if timeAgoNs <= uint(v: 7d) then \"INIT_BUCKET_NAME_5min\"\n  else if timeAgoNs <= uint(v: 90d) then \"INIT_BUCKET_NAME_1h\"\n  else if timeAgoNs <= uint(v: 365d) then \"INIT_BUCKET_NAME_4h\"\n  else if timeAgoNs <= uint(v: 2190d) then \"INIT_BUCKET_NAME_1d\"\n  else \"INIT_BUCKET_NAME_1w\"\nisRaw = timeAgoNs <= uint(v: 3h)\nfield = if isRaw then \"used_percent\" else \"used_percent_max\"\n\nfrom(bucket: bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == field)\n  |> filter(fn: (r) => r[\"path\"] == \"/\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> set(key: \"_field\", value: \"disk_max\")"
    },
    {
     "query": "timeAgoNs = uint(v: now()) - uint(v: v.timeRangeStart)\nbucket = if timeAgoNs <= uint(v: 3h) then \"INIT_BUCKET_NAME\"\n  else if timeAgoNs <= uint(v: 36h) then \"INIT_BUCKET_NAME_1min\"\n  else if timeAgoNs <= uint(v: 7d) then \"INIT_BUCKET_NAME_5min\"\n  else if timeAgoNs <= uint(v: 90d) then \"INIT_BUCKET_NAME_1h\"\n  else if timeAgoNs <= uint(v: 365d) then \"INIT_BUCKET_NAME_4h\"\n  else if timeAgoNs <= uint(v: 2190d) then \"INIT_BUCKET_NAME_1d\"\n  else \"INIT_BUCKET_NAME_1w\"\nisRaw = timeAgoNs <= uint(v: 3h)\nfield = if isRaw then \"used_percent\" else \"used_percent_min\"\n\nfrom(bucket: bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == field)\n  |> filter(fn: (r) => r[\"path\"] == \"/\")\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n  |> set(key: \"_field\", value: \"disk_min\")"
    }
   ]
  },
  {
   "title": "System Load Average (1m, 5m, 15m)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "import \"strings\"\n\ntimeAgoNs = uint(v: now()) - uint(v: v.timeRangeStart)\nbucket = if timeAgoNs <= uint(v: 3h) then \"INIT_BUCKET_NAME\"\n  else if timeAgoNs <= uint(v: 36h) then \"INIT_BUCKET_NAME_1min\"\n  else if timeAgoNs <= uint(v: 7d) then \"INIT_BUCKET_NAME_5min\"\n  else if timeAgoNs <= uint(v: 90d) then \"INIT_BUCKET_NAME_1h\"\n  else if timeAgoNs <= uint(v: 365d) then \"INIT_BUCKET_NAME_4h\"\n  else if timeAgoNs <= uint(v: 2190d) then \"INIT_BUCKET_NAME_1d\"\n  else \"INIT_BUCKET_NAME_1w\"\nisRaw = timeAgoNs <= uint(v: 3h)\nfieldSuffix = if isRaw then \"\" else \"_mean\"\n\nfrom(bucket: bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load1\" + fieldSuffix\n       or r[\"_field\"] == \"load5\" + fieldSuffix\n       or r[\"_field\"] == \"load15\" + fieldSuffix)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: if strings.hasSuffix(v: r._field, suffix: \"_mean\")\n       then strings.trimSuffix(v: r._field, suffix: \"_mean\")\n       else r._field }))"
    },
    {
     "query": "import \"strings\"\n\ntimeAgoNs = uint(v: now()) - uint(v: v.timeRangeStart)\nbucket = if timeAgoNs <= uint(v: 3h) then \"INIT_BUCKET_NAME\"\n  else if timeAgoNs <= uint(v: 36h) then \"INIT_BUCKET_NAME_1min\"\n  else if timeAgoNs <= uint(v: 7d) then \"INIT_BUCKET_NAME_5min\"\n  else if timeAgoNs <= uint(v: 90d) then \"INIT_BUCKET_NAME_1h\"\n  else if timeAgoNs <= uint(v: 365d) then \"INIT_BUCKET_NAME_4h\"\n  else if timeAgoNs <= uint(v: 2190d) then \"INIT_BUCKET_NAME_1d\"\n  else \"INIT_BUCKET_NAME_1w\"\nisRaw = timeAgoNs <= uint(v: 3h)\nfieldSuffix = if isRaw then \"\" else \"_max\"\n\nfrom(bucket: bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load1\" + fieldSuffix\n       or r[\"_field\"] == \"load5\" + fieldSuffix\n       or r[\"_field\"] == \"load15\" + fieldSuffix)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: if strings.hasSuffix(v: r._field, suffix: \"_max\")\n       then strings.trimSuffix(v: r._field, suffix: \"_max\") + \"_max\"\n       else r._field + \"_max\" }))"
    },
    {
     "query": "import \"strings\"\n\ntimeAgoNs = uint(v: now()) - uint(v: v.timeRangeStart)\nbucket = if timeAgoNs <= uint(v: 3h) then \"INIT_BUCKET_NAME\"\n  else if timeAgoNs <= uint(v: 36h) then \"INIT_BUCKET_NAME_1min\"\n  else if timeAgoNs <= uint(v: 7d) then \"INIT_BUCKET_NAME_5min\"\n  else if timeAgoNs <= uint(v: 90d) then \"INIT_BUCKET_NAME_1h\"\n  else if timeAgoNs <= uint(v: 365d) then \"INIT_BUCKET_NAME_4h\"\n  else if timeAgoNs <= uint(v: 2190d) then \"INIT_BUCKET_NAME_1d\"\n  else \"INIT_BUCKET_NAME_1w\"\nisRaw = timeAgoNs <= uint(v: 3h)\nfieldSuffix = if isRaw then \"\" else \"_min\"\n\nfrom(bucket: bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load1\" + fieldSuffix\n       or r[\"_field\"] == \"load5\" + fieldSuffix\n       or r[\"_field\"] == \"load15\" + fieldSuffix)\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: if strings.hasSuffix(v: r._field, suffix: \"_min\")\n       then strings.trimSuffix(v: r._field, suffix: \"_min\") + \"_min\"\n       else r._field + \"_min\" }))"
    }
   ]
  },
  {
   "title": "Network Receive (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "timeAgoNs = uint(v: now()) - uint(v: v.timeRangeStart)\nbucket = if timeAgoNs <= uint(v: 3h) then \"INIT_BUCKET_NAME\"\n  else if timeAgoNs <= uint(v: 36h) then \"INIT_BUCKET_NAME_1min\"\n  else if timeAgoNs <= uint(v: 7d) then \"INIT_BUCKET_NAME_5min\"\n  else if timeAgoNs <= uint(v: 90d) then \"INIT_BUCKET_NAME_1h\"\n  else if timeAgoNs <= uint(v: 365d) then \"INIT_BUCKET_NAME_4h\"\n  else if timeAgoNs <= uint(v: 2190d) then \"INIT_BUCKET_NAME_1d\"\n  else \"INIT_BUCKET_NAME_1w\"\nisRaw = timeAgoNs <= uint(v: 3h)\n\nrawBase = from(bucket: \"INIT_BUCKET_NAME\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => isRaw)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\")\n  |> filter(fn: (r) => r[\"interface\"] != \"lo\")\n  |> derivative(unit: 1s, nonNegative: true)\n\nrawMean = rawBase |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> set(key: \"_field\", value: \"net_recv_mean\")\nrawMin  = rawBase |> aggregateWindow(every: v.windowPeriod, fn: min,  createEmpty: false) |> set(key: \"_field\", value: \"net_recv_min\")\nrawMax  = rawBase |> aggregateWindow(every: v.windowPeriod, fn: max,  createEmpty: false) |> set(key: \"_field\", value: \"net_recv_max\")\n\ndsBase = from(bucket: bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => not isRaw)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\n  |> filter(fn: (r) => r[\"interface\"] != \"lo\")\n\ndsMean = dsBase |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv_mean\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> set(key: \"_field\", value: \"net_recv_mean\")\ndsMin  = dsBase |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv_min\")  |> aggregateWindow(every: v.windowPeriod, fn: min,  createEmpty: false) |> set(key: \"_field\", value: \"net_recv_min\")\ndsMax  = dsBase |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv_max\")  |> aggregateWindow(every: v.windowPeriod, fn: max,  createEmpty: false) |> set(key: \"_field\", value: \"net_recv_max\")\n\nunion(tables: [rawMean, rawMin, rawMax, dsMean, dsMin, dsMax])"
    }
   ]
  },
  {
   "title": "Network Transmit (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "timeAgoNs = uint(v: now()) - uint(v: v.timeRangeStart)\nbucket = if timeAgoNs <= uint(v: 3h) then \"INIT_BUCKET_NAME\"\n  else if timeAgoNs <= uint(v: 36h) then \"INIT_BUCKET_NAME_1min\"\n  else if timeAgoNs <= uint(v: 7d) then \"INIT_BUCKET_NAME_5min\"\n  else if timeAgoNs <= uint(v: 90d) then \"INIT_BUCKET_NAME_1h\"\n  else if timeAgoNs <= uint(v: 365d) then \"INIT_BUCKET_NAME_4h\"\n  else if timeAgoNs <= uint(v: 2190d) then \"INIT_BUCKET_NAME_1d\"\n  else \"INIT_BUCKET_NAME_1w\"\nisRaw = timeAgoNs <= uint(v: 3h)\n\nrawBase = from(bucket: \"INIT_BUCKET_NAME\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => isRaw)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\")\n  |> filter(fn: (r) => r[\"interface\"] != \"lo\")\n  |> derivative(unit: 1s, nonNegative: true)\n\nrawMean = rawBase |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> set(key: \"_field\", value: \"net_send_mean\")\nrawMin  = rawBase |> aggregateWindow(every: v.windowPeriod, fn: min,  createEmpty: false) |> set(key: \"_field\", value: \"net_send_min\")\nrawMax  = rawBase |> aggregateWindow(every: v.windowPeriod, fn: max,  createEmpty: false) |> set(key: \"_field\", value: \"net_send_max\")\n\ndsBase = from(bucket: bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => not isRaw)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\n  |> filter(fn: (r) => r[\"interface\"] != \"lo\")\n\ndsMean = dsBase |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent_mean\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> set(key: \"_field\", value: \"net_send_mean\")\ndsMin  = dsBase |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent_min\")  |> aggregateWindow(every: v.windowPeriod, fn: min,  createEmpty: false) |> set(key: \"_field\", value: \"net_send_min\")\ndsMax  = dsBase |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent_max\")  |> aggregateWindow(every: v.windowPeriod, fn: max,  createEmpty: false) |> set(key: \"_field\", value: \"net_send_max\")\n\nunion(tables: [rawMean, rawMin, rawMax, dsMean, dsMin, dsMax])"
    }
   ]
  }
 ]
}